accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('follow/<str:username>', views.follow, name='follow'),
    path('unfollow/<str:username>', views.unfollow, name='unfollow'),
    path('<str:username>/_saved/', views.profile, name='profile'),
    path('settings/edit-profile/', views.edit_profile, name='edit_profile'),
    path('activate/<str:uidb64>/<str:token>/',
         views.activate_email, name='activate_email'),
    path('verify_email/', views.verify_email, name='verify_email'),
]

boards/urls.py
from django.urls import path

from . import views

app_name = 'boards'

urlpatterns = [
    path('create/', views.create_board, name='create_board'),
    path('<str:username>/<str:board_name>/', views.board_detail, name='board_detail'),
    path('<int:id>/', views.edit_board, name='edit_board'),
    path('save/<int:id>', views.save_to_board, name='save_to_board'),
    path('remove/<int:pin_id>/<int:board_id>/', views.remove_from_board, name='remove_from_board'),
]

pins/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = 'pins'

urlpatterns = [
    path('create/', views.create_pin, name='create_pin'),
    path('edit/<int:id>', views.edit_pin, name='edit_pin'),
    path('delete/<int:id>', views.delete_pin, name='delete_pin'),
    path('comment/<int:id>', views.add_comment, name='add_comment'),
    path('delete-comment/<int:id>', views.delete_comment, name='delete_comment'),
    path('pin/<int:id>/', views.pin_detail, name='pin_detail'),
    path('<str:username>/created/', views.created_pins, name='created_pins'),
]

pinterest/urls.py
from django.urls import path

from .views import home, search

app_name = 'pinterest'

urlpatterns = [
    path('', home, name='home'),
    path('search/', search, name='search'),
]

pinterest_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pinterest.urls', namespace='pinterest')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('boards/', include('boards.urls', namespace='boards')),
    path('pins/', include('pins.urls', namespace='pins')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/activate_email.html
Hello {{ user.username }},
 Please click on the link below to activate your account:
 http://{{ domain }}{% url 'accounts:activate_email' uidb64=uid token=token %}
 Thank you.
 Best regards,
The Team

templates/activate_fail.html
{% extends 'login.html' %}
 {% block content %}
    <h1>Sorry, the activation link is invalid or has expired.</h1>
    <p>Please request a new activation link or contact the support team for assistance.</p>
{% endblock %}

templates/activate_success.html
{% extends 'login.html' %}
 {% block content %}
    <h1>Your account has been activated!</h1>
    <p>You can now log in using your credentials.</p>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'favicon.png' %}"/>
    <!-- bootstrap css cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Pinterest</title>
</head>
<body>
  <header class="p-3 mb-3 bg-white sticky-top">
    <div class="">
      <div class="d-flex flex-wrap align-items-center justify-content-center">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
          <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" class="gUZ lZJ U9O kVc" height="24" width="24" viewBox="0 0 24 24" aria-hidden="true" aria-label="" role="img"><path d="M0 12c0 5.123 3.211 9.497 7.73 11.218-.11-.937-.227-2.482.025-3.566.217-.932 1.401-5.938 1.401-5.938s-.357-.715-.357-1.774c0-1.66.962-2.9 2.161-2.9 1.02 0 1.512.765 1.512 1.682 0 1.025-.653 2.557-.99 3.978-.281 1.189.597 2.159 1.769 2.159 2.123 0 3.756-2.239 3.756-5.471 0-2.861-2.056-4.86-4.991-4.86-3.398 0-5.393 2.549-5.393 5.184 0 1.027.395 2.127.889 2.726a.36.36 0 0 1 .083.343c-.091.378-.293 1.189-.332 1.355-.053.218-.173.265-.4.159-1.492-.694-2.424-2.875-2.424-4.627 0-3.769 2.737-7.229 7.892-7.229 4.144 0 7.365 2.953 7.365 6.899 0 4.117-2.595 7.431-6.199 7.431-1.211 0-2.348-.63-2.738-1.373 0 0-.599 2.282-.744 2.84-.282 1.084-1.064 2.456-1.549 3.235C9.584 23.815 10.77 24 12 24c6.627 0 12-5.373 12-12S18.627 0 12 0 0 5.373 0 12" fill="#E60023" stroke-width="0px"></path></svg>
        </a>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a style='border-radius: 50px; font-size: 15px;' href="#" class="ms-3 nav-link px-2 text-white bg-black"><b>Home</b></a></li>
          <li><a href="#" class="ms-1 nav-link px-2 link-dark"><b>Today</b></a></li>
        </ul>
        <form action="{% url 'pinterest:search' %}" class="col-12 w-75 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input name="q" style="background-color: #e1e1e1;" type="search" class="pt-2 pb-2 form-control border rounded-pill" placeholder="Search" aria-label="Search">
        </form>
        <div class="ms-">
          <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" class="me-3 gUZ B9u U9O kVc" height="24" width="24" viewBox="0 0 24 24" aria-hidden="true" aria-label="" role="img"><path d="M12 24c-1.66 0-3-1.34-3-3h6c0 1.66-1.34 3-3 3zm7-10.83c1.58 1.52 2.67 3.55 3 5.83H2c.33-2.28 1.42-4.31 3-5.83V7c0-3.87 3.13-7 7-7s7 3.13 7 7v6.17z" fill="#767676" stroke-width="0px"></path></svg>
          <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" class="me-3 Hn_ gUZ B9u U9O kVc" height="24" width="24" viewBox="0 0 24 24" aria-hidden="true" aria-label="" role="img"><path d="M18 12.5a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 18 12.5m-6 0a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 12 12.5m-6 0a1.5 1.5 0 1 1 .001-3.001A1.5 1.5 0 0 1 6 12.5M12 0C5.925 0 1 4.925 1 11c0 2.653.94 5.086 2.504 6.986L2 24l5.336-3.049A10.93 10.93 0 0 0 12 22c6.075 0 11-4.925 11-11S18.075 0 12 0" fill="#767676" stroke-width="0px"></path></svg>
        </div>
        <a href="{% url 'accounts:profile' request.user.username %}">
          <img src="{{ request.user.profile.photo.url }}" alt="mdo" width="32" height="32" class="rounded-circle">
        </a>
        <div class="dropdown text-end">
          <a href="#" class="ms-3 d-block link-dark text-decoration-none" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" class="gUZ B9u U9O kVc" height="12" width="12" viewBox="0 0 24 24" aria-hidden="true" aria-label="" role="img"><path d="M12 19.5.66 8.29c-.88-.86-.88-2.27 0-3.14.88-.87 2.3-.87 3.18 0L12 13.21l8.16-8.06c.88-.87 2.3-.87 3.18 0 .88.87.88 2.28 0 3.14L12 19.5z" fill="#767676" stroke-width="0px"></path></svg>
          </a>
          <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
            <li><a class="dropdown-item" href="{% url 'accounts:edit_profile' %}">Settings</a></li>
            <li><a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Sign out</a></li>
          </ul>
        </div>
      </div>
    </div>
  </header>
    <main class="ms-3 me-3">
        <div class="row mt-3">
          <!-- content -->
          {% block content %}{% endblock %}
        </div>
      </main>
    <!-- Bootstrap JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{% static 'main.js' %}"></script>
</body>
</html>

templates/board_detail.html
{% extends "base.html" %}
{% block content %}

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 text-center">
        <h1><b>{{ board.title }}</b></h1>
        {% if request.user == board.user %}
        <a href="{% url 'boards:edit_board' board.id %}" class="text-decoration-none">
            <svg class="main-btn p-1 rounded-circle" class="gUZ pBj U9O kVc" height="25" width="25" viewBox="0 0 24 24" aria-hidden="true" aria-label="" role="img">
                <path d="m13.386 6.018 4.596 4.596L7.097 21.499 1 22.999l1.501-6.096L13.386 6.018zm8.662-4.066a3.248 3.248 0 0 1 0 4.596l-2.298 2.3-4.596-4.598 2.298-2.299a3.248 3.248 0 0 1 4.596 0z"></path>
            </svg>
        </a>
        {% endif %}
        <img style="object-fit: cover;" src="{{ board.cover.url }}" class="rounded-circle" width="60" height="60">
        <div class="mt-2">{{ board.description }}</div>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="row mt-5">
    {% for pin in pins %}
    <div class="img-container col-md-2 mb-3">
        <a href="{% url 'pins:pin_detail' pin.id %}">
            {% if pin.get_type == 'video' %}
                <video autoplay muted loop class="video" >
                    <source src="{{ pin.file.url }}" >
                </video>
            {% elif pin.get_type == 'image' %}
                <img style="object-fit: cover; border-radius: 20px; cursor: zoom-in;" height="300" width="200" src="{{ pin.file.url }}">
            {% endif %}
        </a>
        <div class="dropdown ms-3">
            <a href="#" class="d-block link-dark text-decoration-none" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" class="gUZ pBj" height="20" width="20" viewBox="0 0 24 24" aria-label="More options" role="img">
                    <path d="M12 9c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3M3 9c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3zm18 0c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3z" fill="#111111" stroke-width="0px"></path>
                </svg>
            </a>
            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                <li><a id="editPinBtn" class="dropdown-item" href="{% url 'boards:remove_from_board' pin.id board.id %}">Remove From Board</a></li>
            </ul>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/create_pin.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div style="background-color: #efefef;height: auto;" class="row">
    <div class="col-md-3"></div>
    <div style="border-radius: 15px;" class="col-md-6 mt-5 mb-5 bg-white">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
    <div class="col-md-12 p-5">
        <div class="row">
          <div class="col-md-5"></div>
            <div class="col-md-6"> {{form.board}}</div>
            <div class="col-md-1">
                <button type="submit" class="text-white" style="background-color: #e60023; border-radius: 0 30px 30px 0;border: 0;padding-top: 7px;padding-bottom: 7px;padding-left: 7px;padding-right: 10px;margin-left: -25px;"><b>Save</b></button>
            </div>
            <div class="col-md-12 mt-3">{{form.title}}</div>
            <div class="col-md-12 mt-3">{{form.description}}</div>
            <div class="col-md-12 mt-3">{{form.link}}</div>
            <div class="col-md-12 mt-3 mb-2">{{form.file}}</div>
        </div>
    </form>
    </div>
    </div>
    </div>
    <div class="col-md-3"></div>
</div>
</div>
    {% endblock %}

templates/first_header.html
<div class="p-3 bg-white first-header">
    <div class="d-flex flex-wrap align-items-center justify-content-center">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Pinterest_Logo.svg/1200px-Pinterest_Logo.svg.png" width="120" height="33" alt="">
        </a>
        <ul class="nav ms-5 col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"></ul>
        <div class="dropdown text-end">
        <a class="text-decoration-none text-black me-4" href="#"><b>About</b></a>
        <a class="text-decoration-none text-black me-4" href="#"><b>Business</b></a>
        <a class="text-decoration-none text-black me-5" href="#"><b>Blog</b></a>
        <a href="{% url 'accounts:user_login' %}" id="loginBtn" class="red-btn btn text-white "><b>Login</b></a>
        <a href="{% url 'accounts:user_register' %}" class="main-btn btn text-black ms-3"><b>Sign Up</b></a>
        </div>
    </div>
</div>

templates/home.html
{% extends "base.html" %}
{% block content %}

<div id="masonry">
    {% for pin in pins %}
    <a class="m-2" href="{% url 'pins:pin_detail' pin.id %}">
        {% if pin.get_type == 'video' %}
        <video autoplay muted loop>
            <source src="{{ pin.file.url }}">
        </video>
        {% elif pin.get_type == 'image' %}
        <img src="{{ pin.file.url }}">
        {% endif %}
    </a>
    {% endfor %}
</div>

{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<head>
    <!-- bootstrap css cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Pinterest</title>
</head>

{% include 'first_header.html' %}
<body class="login-bg" style="height: 100vh;">


    <div class="modal-content ps-5 pb-5 pe-5">
        <h3 class="mt-4 mb-3"><b>Login</b></h3>
        <div class="row">
            {% if messages %}
                {% for message in messages %}
                    <center><p class="text-center text-danger">{{ message }}</p></center>
                {% endfor %}
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <div class="">
                    {{ form.username }}
                </div>
                <div class="mt-2">
                    {{ form.password }}
                </div>
                <input class="modal-red-btn btn text-white mt-3 w-100" type="submit" value="Login">
            </form>
            <small class="text-muted mt-3">
                New Here? <a class="text-decoration-none" href="{% url 'accounts:user_register' %}">Create account</a>
            </small>
        </div>
    </div>
</body>
</html>

templates/pin_detail.html
{% extends "base.html" %}
{% block content %}
<div class="col-md-2"></div>
<div class="col-md-8 pt-2 pb-2 row pin-detail-container">
    <div class="col-md-6">
        {% if pin.get_type == 'video' %}
        <video autoplay muted controls class="pin-detail-img">
            <source src="{{ pin.file.url }}">
        </video>
        {% elif pin.get_type == 'image' %}
        <img src="{{ pin.file.url }}" class="pin-detail-img">
        {% endif %}
    </div>
    <div class="col-md-6 mt-4">
        <form action="{% url 'boards:save_to_board' pin.id %}" class="mb-3" method="post">
        <div class="row">
            {% csrf_token %}
            <div class="dropdown col-md-6 mt-2">
                <a href="#" class="d-block link-dark text-decoration-none" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                    <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" class="gUZ pBj" height="20" width="20" viewBox="0 0 24 24" aria-label="More options" role="img">
                        <path d="M12 9c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3M3 9c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3zm18 0c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3z" fill="#111111" stroke-width="0px"></path>
                    </svg>
                </a>
                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                    {% if request.user == pin.user %}
                    <li><a id="editPinBtn" class="dropdown-item" href="#">Edit pin</a></li>
                    {% endif %}
                    <li><a class="dropdown-item" href="{{ pin.file.url }}" download>Download image</a></li>
                </ul>
            </div>
            <div class="col-md-4">{{save_to_board_form.board}}</div>
            <div class="col-md-1">
                <button type="submit" class="save-btn text-white"><b>Save</b></button>
            </div>
        </div>
        </form>
        <p><a class="text-black" href="http://{{pin.link}}">{{ pin.link }}</a></p>
        <h1><b>{{pin.title}}</b></h1>
        <div class="row">
            <div class="col-md-1">
                <a href="{% url 'accounts:profile' pin.user.username %}">
                    <img src="{{ pin.user.profile.photo.url }}" class="rounded-circle" width="50" height="50">
                </a>
            </div>
            <div class="col-md-7 ms-1">
                <a href="{% url 'accounts:profile' pin.user.username %}" class="text-decoration-none text-dark">
                    <b class="ms-3">{{pin.user.username}}</b>
                </a>
                <p class="ms-3" style="font-size: 13px;">{{ pin.user.following.count }} followers</p>
            </div>
            {% if pin.user != request.user %}
            <div class="col-md-1 mt-1">
                {% if is_following %}
                <a href="{% url 'accounts:unfollow' pin.user.username %}" class="following-btn btn text-white"><b>Following</b></a>
                {% else %}
                <a href="{% url 'accounts:follow' pin.user.username %}" class="main-btn btn text-black"><b>Follow</b></a>
                {% endif %}
            </div>
            {% endif %}
        </div>
        <div class="mt-1">{{ pin.description }}</div>
        <h5 class="mt-3">
            <b>Comments</b>
            <a href="#" id="openComments">
                <svg class="mb-1 ms-2 Hn_ gUZ pBj U9O kVc" height="18" width="18" viewBox="0 0 24 24" aria-hidden="true" aria-label="" role="img"><path d="M6.72 24c.57 0 1.14-.22 1.57-.66L19.5 12 8.29.66c-.86-.88-2.27-.88-3.14 0-.87.88-.87 2.3 0 3.18L13.21 12l-8.06 8.16c-.87.88-.87 2.3 0 3.18.43.44 1 .66 1.57.66" fill="#111111" stroke-width="0px"></path></svg>
            </a>
        </h5>
        <form style="display: none;" action="{% url 'pins:add_comment' pin.id %}" id="commentsForm" method="post">
            <p style="font-size: 12px;" >Share feedback, ask a question or give a high five</p>
            {% csrf_token %}
            <div class="row">
                {% for comment in pin.comments.all %}
                <div class="col-md-1 me-4 mt-3">
                    <img src="{{ comment.user.profile.photo.url }}" class="rounded-circle" width="50" height="50">
                </div>
                <div class="col-md-10 mt-1 mb-2">
                    <div class="border p-2 comment-text-border">
                        <span><b>{{ comment.user.username }}</b></span><br>
                        <span class="text-muted">
                            {{ comment.text }}
                        </span>
                    </div>
                    <div class="row">
                        <div class="dropdown col-md-2 ms-3">
                            <a href="#" class="d-block link-dark text-decoration-none" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" class="gUZ B9u U9O kVc" height="16" width="16" viewBox="0 0 24 24" aria-hidden="true" aria-label="" role="img"><path d="M12 9c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3M3 9c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3zm18 0c1.66 0 3 1.34 3 3s-1.34 3-3 3-3-1.34-3-3 1.34-3 3-3z" fill="#767676" stroke-width="0px"></path></svg>
                            </a>
                            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                                <li><a class="dropdown-item" href="{% url 'pins:delete_comment' comment.id %}">Delete</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="row mt-3">
                <div class="col-md-1 me-4">
                    <img src="{{ request.user.profile.photo.url }}" class="rounded-circle" width="50" height="50">
                </div>
                <div class="col-md-10 mt-1">
                    {% csrf_token %}
                    {{ comment_form.text }}
                </div>
            </div>
        </form>
        <div class="mt-5"><b>{{pin.user.username}}</b> saved to <b>{{pin.board.title}}</b></div>
    </div>
</div>
<!-- Edit pin modal -->
<div id="editPinForm" class="modal">
    <div class="row edit-pin-modal p-4">
        <div class="col-md-8">
            <form action="{% url 'pins:edit_pin' pin.id %}" method="post">
                {% csrf_token %}
                {{ edit_form }}
                <button style="float: right;" type="submit" class="mt-3 red-btn btn text-white"><b>Save</b></button>
            </form>
            <div class="mt-3">
                <a href="" style="float: right;" class="main-btn btn me-2 text-black"><b>Cancel</b></a>
                <a href="{% url 'pins:delete_pin' pin.id %}" class="main-btn btn text-black"><b>Delete</b></a>
            </div>
        </div>
        <div class="col-md-4">
            {% if pin.get_type == 'video' %}
            <video class="p-2 edit-modal-video" autoplay muted>
                <source src="{{ pin.file.url }}">
            </video>
            {% elif pin.get_type == 'image' %}
            <img src="{{ pin.file.url }}" class="mt-4 p-2 edit-modal-img" />
            {% endif %}
        </div>
    </div>
</div>
<div class="col-md-2"></div>
<h3 class="text-black text-center mt-3"><b>More like this</b></h3>
<div class="row mt-4">
    {% for pin in related_pins %}
    <div class="img-container col-md-2 mb-3">
        <a href="{% url 'pins:pin_detail' pin.id %}">
            {% if pin.get_type == 'video' %}
                <video autoplay muted loop class="video" >
                    <source src="{{ pin.file.url }}" >
                </video>
            {% elif pin.get_type == 'image' %}
                <img style="object-fit: cover; border-radius: 20px; cursor: zoom-in;" height="300" width="200" src="{{ pin.file.url }}">
            {% endif %}
        </a>
    </div>
    {% endfor %}
</div>

<script>
// comments open and close form in pin detail
const openComments = document.querySelector('#openComments')
const commentsForm = document.querySelector('#commentsForm')

openComments.addEventListener('click', (e) => {
    e.preventDefault()
    if(commentsForm.style.display === 'none'){
        commentsForm.style.display = 'block';
        openComments.innerHTML = '<svg class="mb-1 ms-2 gUZ pBj U9O kVc" height="18" width="18" viewBox="0 0 24 24" aria-label="Select a board you want to save to" role="img"><path d="M12 19.5.66 8.29c-.88-.86-.88-2.27 0-3.14.88-.87 2.3-.87 3.18 0L12 13.21l8.16-8.06c.88-.87 2.3-.87 3.18 0 .88.87.88 2.28 0 3.14L12 19.5z" fill="#111111" stroke-width="0px"></path></svg>'
    } else{
        commentsForm.style.display = 'none';
        openComments.innerHTML = '<svg class="mb-1 ms-2 Hn_ gUZ pBj U9O kVc" height="18" width="18" viewBox="0 0 24 24" aria-hidden="true" aria-label="" role="img"><path d="M6.72 24c.57 0 1.14-.22 1.57-.66L19.5 12 8.29.66c-.86-.88-2.27-.88-3.14 0-.87.88-.87 2.3 0 3.18L13.21 12l-8.06 8.16c-.87.88-.87 2.3 0 3.18.43.44 1 .66 1.57.66" fill="#111111" stroke-width="0px"></path></svg>'
    }
})

// edit pin modal
const editPinBtn = document.querySelector("#editPinBtn");
const editPinForm = document.querySelector("#editPinForm");

editPinBtn.addEventListener("click", (e) => {
  e.preventDefault();
  editPinForm.style.display = "block";
});

window.addEventListener("click", (e) => {
  if (e.target === editPinForm) {
    editPinForm.style.display = "none";
  }
});
</script>


{% endblock %}

templates/register.html
{% load static %}
<!DOCTYPE html>
<head>
    <!-- bootstrap css cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Pinterest</title>
</head>
{% include 'first_header.html' %}
<body class="login-bg" style="height: 100vh;">
    <div class="modal-content ps-5 pb-5 pe-5">
        <h3 class="mt-4 mb-3"><b>Create account</b></h3>
        <div class="row">
            <form method="post">
                {% csrf_token %}
                <div class="">
                    {{ form.email }}
                </div>
                <div class="mt-2">
                    {{ form.username }}
                </div>
                <div class="mt-2">
                    {{ form.password }}
                </div>
                <input class="modal-red-btn btn text-white mt-3 w-100" type="submit" value="Submit">
            </form>
            <small class="text-muted mt-3">
                Already have a account? <a class="text-decoration-none" href="{% url 'accounts:user_login' %}">Login Here</a>
            </small>
        </div>
    </div>
</body>

</html>

templates/verify_email.html
{% extends 'login.html' %}
 {% block content %}
    <h1>Thank you for signing up!</h1>
    <p>Please check your email and follow the instructions to activate your account.</p>
{% endblock %}